version: '3.8'

services:
  # Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: cardiocare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - cardiocare-network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - cardiocare-network

  # Django Backend
  backend:
    build: ./backend
    command: gunicorn cardiocare.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cardiocare
      - REDIS_URL=redis://redis:6379/0
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
      - redis
    networks:
      - cardiocare-network

  # Celery Worker
  celery:
    build: ./backend
    command: celery -A cardiocare worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cardiocare
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - backend
    networks:
      - cardiocare-network

  # Next.js Frontend
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - cardiocare-network

volumes:
  postgres_data:

networks:
  cardiocare-network:
    driver: bridge
